#include "buffer.h"
#include <stdio.h>
#include <pthread.h>

typedef struct SData {
   SBuffer* sb;
   pthread_mutex_t mtx;
   /*
    * Add condition variables required
   */

} SData;

void *consumer(void* consumer_thread_data);
void *producer(void *producer_thread_data);

int main(int argc,char* argv[])
{
  SData shared;
  shared.sb = makeBuffer(32);

  /* TODO
    * Initialize mutexes and condition variables
    * Setup 4 threads. 1 producer and 3 consumers.
    * Make the producer generate "tasks" to compute factorial
    * Make the consumers retrieve task and do them (and print on stdout)
  */

  return 0;
}

long long fact(long long n) {
   if (n==0)
      return 1;
   else return n * fact(n-1);
}

void *producer(void *producer_thread_data) {
   //TODO
   // the producer should produce 10000 tasks - computation of fact of random numbers between 0-15
   // once done, the producer should compute fact of -1 thrice to terminate each of the consumers
   // producer should, therefore, terminate after generating 10000 + 3 tasks
   
}

void *consumer(void* consumer_thread_data) {
   //TODO
   // the consumer should compute factorials of the tasks generated by the producer.
   // if the number read is -1, the consumer should terminate.


}